import type { ProjectContent } from "./project.types";

export const ORDERLY_PROJECT: ProjectContent = {
  id: "orderly",
  year: "2025",
  completedAt: "2025",
  accent: "brand",
  featured: false,
  coverImage: "/assets/orderly/brand/main.png",
  gallery: [
    "/assets/orderly/pages/page-1.png",
    "/assets/orderly/pages/page-2.png",
    "/assets/orderly/pages/page-3.png",
    "/assets/orderly/pages/page-4.png",
    "/assets/orderly/pages/page-5.png",
    "/assets/orderly/pages/page-6.png",
    "/assets/orderly/pages/page-7.png",
    "/assets/orderly/pages/page-8.png",
    "/assets/orderly/pages/page-9.png",
    "/assets/orderly/pages/page-10.png",
    "/assets/orderly/pages/page-11.png",
    "/assets/orderly/pages/page-12.png",
    "/assets/orderly/pages/page-13.png",
    "/assets/orderly/pages/page-14.png",
    "/assets/orderly/pages/page-15.png",
    "/assets/orderly/pages/page-16.png",
    "/assets/orderly/pages/page-17.png",
    "/assets/orderly/pages/page-18.png",
  ],
  tech: [
    "Next.js",
    "React 19",
    "TypeScript",
    "Tailwind CSS 4",
    "next-intl",
    "NextAuth",
    "TanStack Query",
    "Zod",
    "shadcn/ui",
    "Google Maps",
    "Firebase FCM",
    "Recharts",
  ],
  links: [],
  tags: ["team", "frontend"],
  content: {
    en: {
      title: "Orderly",
      category: "Food & Beverage",
      headline: "Orderly — Food Ordering & Restaurant Marketplace",
      cardDescription:
        "Orderly is a bilingual (EN/AR) F&B marketplace for Egypt — dine-in, takeaway, and delivery across restaurants and cafés. Three Next.js apps cover customers, vendor ops, and platform admin, with dual General / GenZ brand modes and full RTL.",
      overview:
        "Orderly is a multi-tenant F&B ordering platform built for the Egyptian market (EGP). Customers discover restaurants and coffee shops, then order dine-in, takeaway, or delivery. Vendors run day-to-day restaurant operations from a permissioned dashboard. Platform admins onboard vendors, manage geography, loyalty rules, coupons, and payouts from a separate CMS. The experience is fully bilingual (English / Arabic) with true RTL, and the customer site offers two visual brand modes — General (teal) and GenZ (purple→mint) — so the same product can speak to different audiences without forking the app.",
      typeLabel: "Frontend development",
      teamLabel: "Team project",
      features: [
        "Three Next.js App Router frontends: customer storefront, vendor ops console, and admin CMS on one REST API",
        "Customer journey: discovery → menu → cart → checkout → order tracking, with loyalty points and referrals",
        "Group cart UX with QR join / share links for shared orders",
        "Three fulfillment modes — dine-in, takeaway, and delivery — with COD checkout",
        "Vendor RBAC: orders, menu CRUD, hot deals, happy hours, branches, Google Maps delivery zones, Excel/PDF exports",
        "Admin CMS: multi-step vendor onboarding, governorates/cities, points rules, coupons, notifications, payouts",
        "Dual theme system (General / GenZ) with Framer Motion switcher and theme-specific fonts and assets",
        "NextAuth JWT sessions, TanStack Query + BFF routes, Firebase FCM push, and full EN/AR RTL",
      ],
      challenges: [
        "Three apps, one product language — consistent shadcn tokens, teal brand, and i18n without a shared package",
        "True RTL + dual themes — fonts, gradients, assets, and sidebar sides resolving per locale × theme",
        "RBAC that doesn’t leak UI — same permission strings through session, sidebar, page guards, and action buttons",
        "Cart complexity — solo cart, group cart (QR/share), and three fulfillment modes with careful state design",
        "Maps in ops vs consumer — address picking for customers vs polygon zones for vendors on the same Maps API",
        "BFF + external API — NextAuth JWT holding the API token while keeping secrets and CORS sane",
        "Export tooling — treating Excel/PDF for ops users as first-class features alongside charts",
      ],
    },
    ar: {
      title: "Orderly",
      category: "طعام ومشروبات",
      headline: "Orderly — منصة طلب طعام وسوق مطاعم",
      cardDescription:
        "Orderly سوق طعام ثنائي اللغة (EN/AR) لمصر — تناول في المكان، سفري، وتوصيل عبر المطاعم والمقاهي. ثلاثة تطبيقات Next.js للعملاء وتشغيل البائعين وإدارة المنصة، مع وضعَي علامة General وGenZ ودعم RTL كامل.",
      overview:
        "Orderly منصة طلب طعام متعددة المستأجرين للسوق المصري (جنيه). يكتشف العملاء المطاعم والمقاهي ثم يطلبون تناولًا في المكان أو سفريًا أو توصيلًا. يدير البائعون تشغيل المطعم اليومي من لوحة بصلاحيات. ويدير مشغّلو المنصة البائعين والجغرافيا وقواعد الولاء والكوبونات والمدفوعات من لوحة إدارة منفصلة. التجربة ثنائية اللغة بالكامل مع RTL حقيقي، وموقع العملاء يقدّم وضعين بصريين — General (فيروزي) وGenZ (بنفسجي→نعناعي) — ليتحدث المنتج لجماهير مختلفة دون تفريع التطبيق.",
      typeLabel: "تطوير واجهات",
      teamLabel: "مشروع فريق",
      features: [
        "ثلاث واجهات Next.js App Router: متجر عملاء، لوحة بائع، ولوحة إدارة على API واحد",
        "رحلة العميل: اكتشاف → قائمة → سلة → دفع → تتبع طلب، مع نقاط ولاء وإحالات",
        "سلة جماعية مع انضمام عبر QR وروابط مشاركة",
        "ثلاثة أوضاع تنفيذ — تناول في المكان، سفري، وتوصيل — مع دفع عند الاستلام",
        "صلاحيات البائع: طلبات، قائمة، عروض، ساعات سعيدة، فروع، مناطق توصيل على الخرائط، وتصدير Excel/PDF",
        "لوحة إدارة: تسجيل بائعين متعدد الخطوات، محافظات/مدن، قواعد نقاط، كوبونات، إشعارات، ومدفوعات",
        "نظام ثيم مزدوج (General / GenZ) مع تبديل Framer Motion وخطوط وأصول حسب الثيم",
        "جلسات NextAuth وTanStack Query وBFF وإشعارات FCM ودعم EN/AR RTL كامل",
      ],
      challenges: [
        "ثلاثة تطبيقات ولغة منتج واحدة — ثبات التوكنات والهوية والترجمة بلا حزمة مشتركة",
        "RTL حقيقي + ثيمين — خطوط وتدرجات وأصول وجانب الشريط حسب اللغة × الثيم",
        "صلاحيات لا تتسرب في الواجهة — نفس سلاسل الصلاحية عبر الجلسة والشريط والحراسة والأزرار",
        "تعقيد السلة — فردية وجماعية وثلاثة أوضاع تنفيذ مع حالة دقيقة",
        "خرائط للمستهلك مقابل التشغيل — اختيار عنوان مقابل مضلعات مناطق التوصيل",
        "BFF + API خارجي — JWT يحمل توكن الـ API مع أسرار وCORS سليمة",
        "أدوات التصدير — اعتبار Excel/PDF ميزات أساسية لفرق التشغيل",
      ],
    },
    fr: {
      title: "Orderly",
      category: "Food & beverage",
      headline: "Orderly — Commande repas & marketplace restaurants",
      cardDescription:
        "Orderly est une marketplace F&B bilingue (EN/AR) pour l'Égypte — sur place, à emporter et livraison. Trois apps Next.js pour clients, ops vendeurs et admin plateforme, avec modes General / GenZ et RTL complet.",
      overview:
        "Orderly est une plateforme de commande F&B multi-tenant pour le marché égyptien (EGP). Les clients découvrent restaurants et cafés, puis commandent sur place, à emporter ou en livraison. Les vendeurs gèrent l'ops quotidien depuis un dashboard permissionné. Les admins onboardent les vendeurs, gèrent géographie, fidélité, coupons et payouts via un CMS séparé. L'expérience est bilingue avec vrai RTL, et le site client propose deux modes de marque — General (teal) et GenZ (violet→menthe) — pour parler à des audiences différentes sans forker l'app.",
      typeLabel: "Développement frontend",
      teamLabel: "Projet d'équipe",
      features: [
        "Trois frontends Next.js App Router : storefront client, console vendeur et CMS admin sur une API REST",
        "Parcours client : découverte → menu → panier → checkout → suivi, avec points fidélité et parrainage",
        "Panier de groupe avec QR join / liens de partage",
        "Trois modes — sur place, à emporter, livraison — avec paiement COD",
        "RBAC vendeur : commandes, menu CRUD, hot deals, happy hours, branches, zones Maps, exports Excel/PDF",
        "CMS admin : onboarding vendeurs, governorates/cities, règles de points, coupons, notifications, payouts",
        "Système dual theme (General / GenZ) avec switcher Framer Motion et assets dédiés",
        "NextAuth JWT, TanStack Query + BFF, FCM, et EN/AR RTL complet",
      ],
      challenges: [
        "Trois apps, un langage produit — tokens shadcn, marque teal et i18n sans package partagé",
        "Vrai RTL + dual themes — fonts, gradients, assets et sidebars selon locale × theme",
        "RBAC sans fuite UI — mêmes permissions via session, sidebar, guards et boutons",
        "Complexité panier — solo, groupe (QR/share) et trois modes de fulfillment",
        "Maps ops vs consumer — adresse client vs polygones de zones vendeur",
        "BFF + API externe — JWT NextAuth portant le token API avec secrets/CORS sains",
        "Exports Excel/PDF traités comme features first-class pour l'ops",
      ],
    },
  },
};
