import type { ProjectContent } from "./project.types";

export const TASWERA_PROJECT: ProjectContent = {
  id: "taswera",
  year: "2024",
  completedAt: "2024",
  accent: "info",
  featured: false,
  coverImage: "/assets/taswera/brand/main.png",
  gallery: [
    "/assets/taswera/pages/page-1.png",
    "/assets/taswera/pages/page-2.png",
    "/assets/taswera/pages/page-3.png",
    "/assets/taswera/pages/page-4.png",
    "/assets/taswera/pages/page-5.png",
    "/assets/taswera/pages/page-6.png",
    "/assets/taswera/pages/page-7.png",
    "/assets/taswera/pages/page-8.png",
    "/assets/taswera/pages/page-9.png",
  ],
  tech: [
    "Next.js 14",
    "React 18",
    "TypeScript",
    "Tailwind CSS",
    "TanStack Query",
    "next-intl",
    "Fabric.js",
    "NextAuth",
    "Zod",
    "shadcn/ui",
    "Recharts",
    "xlsx",
  ],
  links: [],
  tags: ["team", "frontend"],
  content: {
    en: {
      title: "Taswera",
      category: "Event Tech",
      headline: "Taswera — Event Photo-Booth Platform",
      cardDescription:
        "Taswera is an end-to-end event photo-booth product: guests unlock shots with a wristband barcode, edit in a Fabric.js studio, then print or download — while branch teams and HQ run barcodes, uploads, payments, print queues, and sync health across three Next.js apps.",
      overview:
        "Taswera is an end-to-end photo-booth platform for events and venues. Guests receive a wristband with a 5-character barcode, get photographed on-site, then open a kiosk/web experience to select photos, set print sizes, edit with frames, filters, and stickers, and collect prints. Branch staff run upload → order → payment → print/send workflows. HQ admins manage branches and monitor sync health across locations. The product splits into three Next.js frontends sharing one domain spine: barcode → photos → order → print/send → sync — with full English/Arabic RTL.",
      typeLabel: "Frontend development",
      teamLabel: "Team project",
      features: [
        "Guest journey: barcode + phone login, gallery multi-select with Small/Large quantities, Fabric editor, print, checkout, thanks, and post-pay download",
        "In-browser Fabric.js editor — crop, frames, filters, stickers, brightness — with high-res PNG export for print",
        "Cookie + middleware access control (no traditional guest accounts); paid users route to download-only mode",
        "Branch ops dashboard: barcode generate/reset, photographer uploads, orders/pay with shifts, ready-to-print, ZIP archives, Excel/PDF exports",
        "HQ online dashboard: branch CRUD, sync-job analytics, payments filters, global frames & stickers settings",
        "Bilingual product (en/ar) with next-intl, Homenaje + Almarai, and mirrored clip-path CTAs for RTL",
        "Shared brand system: #202020 CTAs, shadcn/Radix, TanStack Query, Zod forms, Sonner toasts",
        "CORS image proxy and print-ready export pipeline (up to ~3000×4500) for reliable booth editing",
      ],
      challenges: [
        "Fabric.js + CORS + print resolution — same-origin image proxy and careful high-DPI export without blowing memory limits",
        "Designing UX around a 5-character wristband code instead of email/password, with custom cookie middleware",
        "Three frontends and two APIs — guest + branch vs HQ online — joined through sync jobs",
        "RTL as first-class layout for clip-path CTAs, mirrored chrome, and bilingual fonts",
        "Same brand tokens across calm kiosk UI and dense admin tables without forcing one layout language",
        "Selection state complexity — order badges, dual size quantities, and clone-before-edit before the editor",
      ],
    },
    ar: {
      title: "تصويرة",
      category: "تقنية فعاليات",
      headline: "تصويرة (Taswera) — منصة كشك صور للفعاليات",
      cardDescription:
        "تصويرة منتج متكامل لكشك الصور في الفعاليات: الضيف يفتح الصور بباركود السوار، يعدّل في محرر Fabric.js، ثم يطبع أو يحمّل — بينما فرق الفروع والإدارة المركزية تدير الباركودات والرفع والمدفوعات وطوابير الطباعة ومزامنة الفروع عبر ثلاثة تطبيقات Next.js.",
      overview:
        "تصويرة منصة كشك صور من طرف إلى طرف للفعاليات والأماكن. يحصل الضيوف على سوار بباركود من 5 أحرف، يُصوَّرون في الموقع، ثم يفتحون تجربة كشك/ويب لاختيار الصور وتحديد أحجام الطباعة والتعديل بالإطارات والفلاتر والملصقات واستلام المطبوعات. يدير فريق الفرع سير الرفع → الطلب → الدفع → الطباعة/الإرسال. وتدير الإدارة المركزية الفروع وتراقب صحة المزامنة. المنتج ثلاثة واجهات Next.js تشترك في مسار واحد: باركود → صور → طلب → طباعة/إرسال → مزامنة — مع إنجليزي وعربي وRTL كامل.",
      typeLabel: "تطوير واجهات",
      teamLabel: "مشروع فريق",
      features: [
        "رحلة الضيف: دخول بباركود وهاتف، معرض متعدد الاختيار بأحجام صغير/كبير، محرر Fabric، طباعة، دفع، شكر، وتحميل بعد الدفع",
        "محرر Fabric.js في المتصفح — قص، إطارات، فلاتر، ملصقات، سطوع — مع تصدير PNG عالي الدقة للطباعة",
        "تحكم وصول عبر الكوكيز والـ middleware (بدون حسابات تقليدية)؛ المدفوعون يُوجَّهون لوضع التحميل فقط",
        "لوحة فرع: توليد/إعادة ضبط باركود، رفع المصورين، طلبات/دفع مع الورديات، جاهز للطباعة، أرشيف ZIP، وتصدير Excel/PDF",
        "لوحة HQ: إدارة الفروع، إحصاءات المزامنة، فلاتر المدفوعات، وإعدادات الإطارات والملصقات",
        "منتج ثنائي اللغة (en/ar) مع next-intl وخطوط Homenaje وAlmarai وأزرار clip-path معكوسة لـ RTL",
        "نظام علامة موحد: أزرار #202020 وshadcn وTanStack Query ونماذج Zod",
        "وكيل صور CORS ومسار تصدير جاهز للطباعة (~3000×4500) لتحرير موثوق في الكشك",
      ],
      challenges: [
        "Fabric.js مع CORS ودقة الطباعة — وكيل صور من نفس الأصل وتصدير عالي الدقة دون استهلاك الذاكرة",
        "تصميم تجربة حول باركود من 5 أحرف بدل البريد/كلمة المرور مع middleware للكوكيز",
        "ثلاث واجهات وواجهتان خلفيتان — ضيف + فرع مقابل HQ — مربوطتان بمهام المزامنة",
        "RTL كتخطيط أساسي للأزرار والكروم والخطوط ثنائية اللغة",
        "نفس رموز العلامة بين واجهة كشك هادئة وجداول إدارة كثيفة",
        "تعقيد حالة الاختيار — شارات الترتيب وكميات الحجمين والاستنساخ قبل المحرر",
      ],
    },
    fr: {
      title: "Taswera",
      category: "Event tech",
      headline: "Taswera — Plateforme photo-booth événementielle",
      cardDescription:
        "Taswera est un produit photo-booth de bout en bout : les invités déverrouillent leurs photos avec un bracelet barcode, éditent dans Fabric.js, puis impriment ou téléchargent — pendant que branches et HQ gèrent barcodes, uploads, paiements, files d'impression et sync via trois apps Next.js.",
      overview:
        "Taswera est une plateforme photo-booth de bout en bout pour événements et venues. Les invités reçoivent un bracelet à barcode 5 caractères, sont photographiés sur site, puis ouvrent une expérience kiosk/web pour sélectionner, choisir les formats d'impression, éditer avec frames/filtres/stickers et récupérer les tirages. Les équipes de branche gèrent upload → commande → paiement → print/send. Le HQ administre les branches et surveille la sync. Trois frontends Next.js partagent un spine : barcode → photos → order → print/send → sync — avec EN/AR et RTL complet.",
      typeLabel: "Développement frontend",
      teamLabel: "Projet d'équipe",
      features: [
        "Parcours invité : login barcode + téléphone, galerie multi-select Small/Large, éditeur Fabric, print, checkout, thanks et download post-paiement",
        "Éditeur Fabric.js in-browser — crop, frames, filtres, stickers, luminosité — avec export PNG haute rés pour l'impression",
        "Contrôle d'accès cookie + middleware (pas de comptes invités classiques) ; payés redirigés vers download-only",
        "Dashboard branche : generate/reset barcodes, uploads photographes, orders/pay avec shifts, ready-to-print, ZIP, exports Excel/PDF",
        "Dashboard HQ : CRUD branches, analytics sync-jobs, filtres paiements, settings frames & stickers",
        "Produit bilingue (en/ar) avec next-intl, Homenaje + Almarai, et CTAs clip-path mirroirés pour RTL",
        "Design system partagé : CTAs #202020, shadcn/Radix, TanStack Query, formulaires Zod",
        "Proxy CORS images et pipeline d'export print-ready (~3000×4500) pour un éditeur booth fiable",
      ],
      challenges: [
        "Fabric.js + CORS + résolution print — proxy same-origin et export haute DPI sans exploser la mémoire",
        "UX autour d'un code bracelet 5 caractères au lieu d'email/password, avec middleware cookies custom",
        "Trois frontends et deux APIs — guest + branche vs HQ — reliés par les sync jobs",
        "RTL comme layout first-class pour CTAs clip-path, chrome mirroiré et polices bilingues",
        "Mêmes tokens de marque entre UI kiosk calme et tables admin denses",
        "Complexité de sélection — badges d'ordre, quantités dual size et clone-before-edit avant l'éditeur",
      ],
    },
  },
};
