import type { ProjectContent } from "./project.types";

export const TIBBI_PROJECT: ProjectContent = {
  id: "tibbi",
  company: "evyx",
  year: "2025",
  completedAt: "2025",
  accent: "brand",
  coverImage: "/assets/tibbi/brand/main.png",
  brandImages: [
    "/assets/tibbi/brand/main.png",
    "/assets/tibbi/brand/main-splash.png",
    "/assets/tibbi/brand/sub-preview.png",
    "/assets/tibbi/brand/third-preview.png",
    "/assets/tibbi/brand/force-preview.png",
  ],
  gallery: [
    "/assets/tibbi/brand/main-splash.png",
    "/assets/tibbi/brand/wallet.png",
    "/assets/tibbi/brand/paymnet.png",
    "/assets/tibbi/pages/booking.png",
    "/assets/tibbi/pages/doctors.png",
    "/assets/tibbi/pages/homevisite.png",
    "/assets/tibbi/pages/services.png",
    "/assets/tibbi/pages/wallet-page.png",
  ],
  tech: [
    "React 18",
    "Vite",
    "TanStack Query",
    "Tailwind CSS",
    "Material UI",
    "Formik",
    "Yup",
    "Firebase FCM",
    "Framer Motion",
    "xlsx",
    "i18next",
  ],
  links: [],
  tags: ["team", "frontend"],
  content: {
    en: {
      title: "Tebbie",
      category: "Healthcare",
      headline: "Tebbie (طبي) — Healthcare Operations Platform",
      cardDescription:
        "Tebbie is a healthcare operations platform for Libyan hospitals and medical providers — clinic bookings, home visits, wallets, staff roles, and a full admin console. Two React apps share one backend: a mobile-first hospital dashboard and a platform control plane for ops, finance, and support.",
      overview:
        "Tebbie is a digital healthcare operations platform that connects hospitals, doctors, medical service providers, and patients across Libya. It covers in-clinic appointments, home-visit services (doctor, nursing, physiotherapy), payments and wallets, staff permissions, reviews, and refunds. The product ships as two React web apps — Tebbie Hospital for day-to-day clinic and visit operations, and Tebbie Admin for multi-hospital control, geography, finance, CMS, WhatsApp, and customer-service chat — both talking to a shared backend API with JWT auth and fine-grained RBAC.",
      typeLabel: "Frontend development",
      teamLabel: "Team project",
      features: [
        "Mobile-first Arabic RTL hospital dashboard with bottom navigation and dual modes (hospital clinics vs medical-service packages)",
        "Clinic specializations, doctors, and booking flows with attendance, approve, cancel, and reschedule",
        "Home visits by profession — doctor, nursing, physiotherapy — with regions, pricing, and live status",
        "Wallet balances, transaction history, and one-click Excel export for bookings, visits, and money flows",
        "Employees, roles, and permission-gated UI so staff only see what their role allows",
        "Firebase Cloud Messaging for foreground push and WebView FCM token handling on login",
        "Admin console: hospitals, doctors, geo (states/cities/regions), wallets, commissions, and financial charts",
        "Platform CMS, push notifications, WhatsApp settings, and WebSocket customer-service chat",
      ],
      challenges: [
        "One hospital codebase serving two product modes with different dashboards and navigation trees",
        "Permission-first UI that stays usable when many actions are hidden by RBAC",
        "Ops-grade booking rules — attendance for today vs future dates, reschedule, and lab PDF uploads",
        "Home-visit logistics across regions, pricing, and multi-profession visit types",
        "Realtime push in WebViews and CS chat over WebSockets with careful token lifecycle handling",
        "RTL hospital UX plus bilingual admin (Arabic / English) with consistent direction and copy",
        "Turning live API lists into Excel exports without blocking the UI",
      ],
    },
    ar: {
      title: "طبي",
      category: "رعاية صحية",
      headline: "طبي (Tebbie) — منصة تشغيل للرعاية الصحية",
      cardDescription:
        "طبي منصة تشغيل صحية للمستشفيات ومقدمي الخدمات الطبية في ليبيا — حجوزات عيادات، زيارات منزلية، محافظ، أدوار الموظفين، ولوحة إدارة كاملة. تطبيقان بـ React على خلفية مشتركة: لوحة مستشفى للجوال ولوحة منصة للتشغيل والمالية والدعم.",
      overview:
        "طبي منصة رقمية لتشغيل الرعاية الصحية تربط المستشفيات والأطباء ومقدمي الخدمات الطبية والمرضى في ليبيا. تغطي مواعيد العيادات، الزيارات المنزلية (طبيب / تمريض / علاج طبيعي)، المدفوعات والمحافظ، صلاحيات الموظفين، التقييمات، والاستردادات. المنتج يتكون من تطبيقين بـ React — تطبيق المستشفى للتشغيل اليومي، ولوحة الإدارة للتحكم متعدد المستشفيات والجغرافيا والمالية والمحتوى والواتساب ودردشة خدمة العملاء — وكلاهما يتصل بواجهة خلفية مشتركة مع JWT وصلاحيات دقيقة.",
      typeLabel: "تطوير واجهات",
      teamLabel: "مشروع فريق",
      features: [
        "لوحة مستشفى للجوال بعربية وRTL مع تنقل سفلي ووضعَين (عيادات مستشفى مقابل باقات خدمات طبية)",
        "تخصصات وعيادات وأطباء وتدفقات حجز مع تأكيد الحضور والموافقة والإلغاء وإعادة الجدولة",
        "زيارات منزلية حسب المهنة — طبيب، تمريض، علاج طبيعي — مع مناطق وتسعير وحالة مباشرة",
        "محافظ ومعاملات وتصدير Excel للحجوزات والزيارات والتدفقات المالية",
        "موظفون وأدوار وواجهة مقيدة بالصلاحيات بحيث يرى كل موظف ما يخصه فقط",
        "إشعارات Firebase FCM في المقدمة ودعم رمز WebView عند تسجيل الدخول",
        "لوحة إدارة: مستشفيات، أطباء، جغرافيا، محافظ، عمولات، ورسوم بيانية مالية",
        "محتوى المنصة، إشعارات الدفع، إعدادات واتساب، ودردشة خدمة العملاء عبر WebSocket",
      ],
      challenges: [
        "قاعدة مستشفى واحدة تخدم وضعين منتجين بلوحات وتنقل مختلفين",
        "واجهة قائمة على الصلاحيات تبقى قابلة للاستخدام عند إخفاء كثير من الإجراءات",
        "قواعد حجز تشغيلية — حضور اليوم مقابل المواعيد المستقبلية وإعادة الجدولة ورفع ملفات المختبر",
        "لوجستيات الزيارات المنزلية عبر المناطق والتسعير وأنواع المهن المتعددة",
        "الإشعارات الفورية في WebView ودردشة الدعم عبر WebSockets مع دورة حياة دقيقة للتوكن",
        "تجربة RTL للمستشفى ولوحة إدارة ثنائية اللغة مع اتجاه ونصوص متسقة",
        "تحويل قوائم الـ API الحية إلى Excel دون تعطيل الواجهة",
      ],
    },
    fr: {
      title: "Tebbie",
      category: "Santé",
      headline: "Tebbie (طبي) — Plateforme d'opérations de santé",
      cardDescription:
        "Tebbie est une plateforme d'opérations de santé pour hôpitaux et prestataires médicaux en Libye — rendez-vous cliniques, visites à domicile, wallets, rôles staff et console admin complète. Deux apps React partagent un backend : dashboard hôpital mobile-first et plan de contrôle plateforme.",
      overview:
        "Tebbie est une plateforme digitale d'opérations de santé qui connecte hôpitaux, médecins, prestataires et patients en Libye. Elle couvre les rendez-vous en clinique, les visites à domicile (médecin / infirmier / kiné), paiements et wallets, permissions staff, avis et remboursements. Le produit est livré en deux apps React — Tebbie Hospital pour l'ops quotidien, et Tebbie Admin pour le multi-hôpital, la géo, la finance, le CMS, WhatsApp et le chat support — branchées sur une API partagée avec JWT et RBAC fin.",
      typeLabel: "Développement frontend",
      teamLabel: "Projet d'équipe",
      features: [
        "Dashboard hôpital mobile-first, arabe RTL, avec bottom nav et double mode (cliniques vs packages médicaux)",
        "Spécialisations, médecins et flux de booking avec présence, approve, cancel et reschedule",
        "Visites à domicile par métier — médecin, nursing, physio — avec régions, pricing et statuts live",
        "Wallets, historique de transactions et export Excel pour bookings, visites et flux argent",
        "Employés, rôles et UI gated par permissions pour que chacun ne voie que son périmètre",
        "Firebase Cloud Messaging en foreground et token FCM WebView au login",
        "Console admin : hôpitaux, médecins, géo, wallets, commissions et charts financiers",
        "CMS plateforme, push notifications, WhatsApp et chat CS via WebSocket",
      ],
      challenges: [
        "Une codebase hôpital pour deux modes produit avec dashboards et nav différents",
        "UI permission-first encore utilisable quand beaucoup d'actions sont masquées par le RBAC",
        "Règles booking ops — présence aujourd'hui vs futures dates, reschedule et upload PDF labo",
        "Logistique home-visit : régions, pricing et types multi-métiers",
        "Push temps réel en WebView et chat CS WebSocket avec cycle de vie token soigné",
        "UX RTL hôpital + admin bilingue (AR / EN) avec direction et copy cohérentes",
        "Exporter des listes API live en Excel sans bloquer l'UI",
      ],
    },
  },
};
