import type { ProjectContent } from "./project.types";

export const TRADE_LINK_PROJECT: ProjectContent = {
  id: "trade-link",
  company: "xai",
  year: "2024",
  completedAt: "2024",
  accent: "info",
  featured: false,
  coverImage: "/assets/trade-link/brand/main.png",
  brandImages: [
    "/assets/trade-link/brand/main.png",
    "/assets/trade-link/brand/sub-preview.png",
    "/assets/trade-link/brand/third-preview.png",
  ],
  gallery: [
    "/assets/trade-link/pages/page-1.png",
    "/assets/trade-link/pages/page-2.png",
    "/assets/trade-link/pages/page-3.png",
    "/assets/trade-link/pages/page-4.png",
    "/assets/trade-link/pages/page-5.png",
    "/assets/trade-link/pages/page-6.png",
    "/assets/trade-link/pages/page-7.png",
    "/assets/trade-link/pages/page-8.png",
    "/assets/trade-link/pages/page-9.png",
    "/assets/trade-link/pages/page-10.png",
    "/assets/trade-link/pages/page-11.png",
    "/assets/trade-link/pages/page-13.png",
    "/assets/trade-link/pages/page-14.png",
  ],
  tech: [
    "Next.js",
    "React 18",
    "TypeScript",
    "Tailwind CSS",
    "MUI",
    "React Query",
    "Redux Toolkit",
    "Socket.IO",
    "Firebase FCM",
    "Axios",
    "Zustand",
    "xlsx",
  ],
  links: [],
  tags: ["team", "frontend"],
  content: {
    en: {
      title: "Trade Link",
      category: "B2B Marketplace",
      headline: "Trade Link — B2B Commodity Brokerage Platform",
      cardDescription:
        "Trade Link is a dual-frontend B2B platform that connects buyers, sellers, and brokers around tradable goods. A public marketplace for discovery and deal chats pairs with a broker portal for catalog, suppliers, transaction timelines, and trade networks.",
      overview:
        "Trade Link is a dual-frontend platform that connects buyers, sellers, and brokers around tradable goods — commodities, energy, textiles, raw materials, food & beverages, and more. The public marketplace helps visitors discover categories, products, and brokers, then start a Chat For A Deal tied to a listing. The broker portal lets brokers CRUD products and suppliers, advance transactions through a six-step status timeline, invite colleagues into a Trade Network tree, and (for admins) govern categories and broker accounts — all on shared identity with JWT cookies, refresh rotation, and role-aware navigation.",
      typeLabel: "Frontend development",
      teamLabel: "Team project",
      features: [
        "Public marketplace: home, explore filters, product detail with Chat For A Deal, broker directory and profiles",
        "Realtime Socket.IO messaging with conversation create/check from product pages",
        "Broker portal: dashboard KPIs, product/supplier/transaction DataGrids, Excel export, AI PDF product intake",
        "Six-step transaction timeline from Initiated through Completed with role-aware buyer/seller actions",
        "Trade Network org chart with email invites for brokerage teams",
        "Marketplace i18n (en / ar / fr) with RTL, plus FCM registration and PWA caching",
        "Cookie JWT auth with refresh queues; portal RBAC for broker vs admin navigation",
        "Brand-consistent UI across Tailwind storefront and MUI portal around #4680FF",
      ],
      challenges: [
        "Two design systems, one brand — aligning Tailwind storefront and MUI portal without a shared component library",
        "Auth across surfaces — cookie JWT + refresh, middleware only on chats vs admin-gated portal routes",
        "Bridging product detail → conversation → Socket.IO rooms while keeping SSR-safe Axios",
        "RBAC data scoping — broker /my endpoints vs admin dashboard APIs",
        "Shipping domain features on top of ecommerce/admin template heritage without a full rewrite",
        "Encoding a six-status transaction lifecycle as a clear vertical timeline with document upload",
        "Real marketplace i18n/RTL while portal localization stayed scaffolding-only",
      ],
    },
    ar: {
      title: "Trade Link",
      category: "سوق B2B",
      headline: "Trade Link — منصة وساطة سلع بين الشركات",
      cardDescription:
        "Trade Link منصة ثنائية الواجهة تربط المشترين والبائعين والوسطاء حول السلع القابلة للتداول. سوق عام للاكتشاف ومحادثات الصفقات، ولوحة وسيط للكتالوج والموردين ومسار المعاملات وشبكات التجارة.",
      overview:
        "Trade Link منصة بواجهتين تربط المشترين والبائعين والوسطاء حول السلع — الطاقة، المنسوجات، المواد الخام، الأغذية والمشروبات والمزيد. يساعد السوق العام الزوار على اكتشاف التصنيفات والمنتجات والوسطاء ثم بدء محادثة صفقة مرتبطة بإعلان. تتيح لوحة الوسيط إدارة المنتجات والموردين، وتقدّم المعاملات عبر مسار حالة من ست خطوات، ودعوة الزملاء إلى شبكة تجارة، وللمشرفين إدارة التصنيفات وحسابات الوسطاء — بهوية مشتركة وJWT وصلاحيات حسب الدور.",
      typeLabel: "تطوير واجهات",
      teamLabel: "مشروع فريق",
      features: [
        "سوق عام: الرئيسية، فلاتر الاستكشاف، تفاصيل المنتج مع Chat For A Deal، دليل الوسطاء وملفاتهم",
        "مراسلة فورية عبر Socket.IO مع إنشاء/استئناف محادثة من صفحة المنتج",
        "لوحة وسيط: مؤشرات، جداول منتجات/موردين/معاملات، تصدير Excel، ورفع PDF بالذكاء الاصطناعي",
        "مسار معاملة من ست خطوات من البدء حتى الإكمال بإجراءات حسب دور المشتري/البائع",
        "شبكة تجارة بمخطط تنظيمي ودعوات بريدية لفرق الوساطة",
        "تعدد لغات السوق (en / ar / fr) مع RTL وإشعارات FCM وPWA",
        "مصادقة JWT بالكوكي مع تحديث الجلسة؛ صلاحيات وسيط مقابل مشرف في اللوحة",
        "هوية بصرية متسقة عبر Tailwind وMUI حول #4680FF",
      ],
      challenges: [
        "نظاما تصميم وهوية واحدة — محاذاة سوق Tailwind ولوحة MUI بلا مكتبة مكوّنات مشتركة",
        "مصادقة عبر السطحين — JWT وتحديث الجلسة، وحماية المسارات حسب الدور",
        "ربط تفاصيل المنتج بالمحادثة وغرف Socket.IO مع Axios آمن للـ SSR",
        "نطاق بيانات RBAC — نقاط /my للوسيط مقابل واجهات المشرف",
        "تسليم ميزات المجال فوق قوالب جاهزة دون إعادة كتابة كاملة",
        "تمثيل دورة حياة المعاملة بست حالات في خط زمني واضح مع رفع المستندات",
        "i18n/RTL حقيقي للسوق بينما بقيت ترجمة اللوحة تمهيدية فقط",
      ],
    },
    fr: {
      title: "Trade Link",
      category: "Marketplace B2B",
      headline: "Trade Link — Plateforme de courtage B2B",
      cardDescription:
        "Trade Link est une plateforme dual-frontend qui relie acheteurs, vendeurs et courtiers autour de biens négociables. Un marketplace public pour la découverte et les chats de deal, et un portail courtier pour catalogue, fournisseurs, timelines et réseaux.",
      overview:
        "Trade Link est une plateforme à deux frontends qui connecte acheteurs, vendeurs et courtiers autour de biens négociables — commodities, énergie, textiles, matières premières, food & beverages, et plus. Le marketplace public aide à découvrir catégories, produits et courtiers, puis à lancer un Chat For A Deal lié à une annonce. Le portail courtier permet le CRUD produits/fournisseurs, l'avancement des transactions sur une timeline à six étapes, l'invitation dans un Trade Network, et (admins) la gouvernance catégories/courtiers — identité partagée JWT, refresh et navigation par rôle.",
      typeLabel: "Développement frontend",
      teamLabel: "Projet d'équipe",
      features: [
        "Marketplace public : home, filtres explore, fiche produit Chat For A Deal, annuaire et profils courtiers",
        "Messagerie Socket.IO temps réel avec create/check conversation depuis la fiche produit",
        "Portail courtier : KPIs, DataGrids produits/fournisseurs/transactions, export Excel, intake PDF IA",
        "Timeline transaction à six étapes d'Initiated à Completed avec actions buyer/seller",
        "Trade Network en org chart avec invites email",
        "i18n marketplace (en / ar / fr) + RTL, FCM et PWA",
        "Auth JWT cookies + refresh ; RBAC broker vs admin sur le portail",
        "UI cohérente Tailwind + MUI autour de #4680FF",
      ],
      challenges: [
        "Deux design systems, une marque — aligner storefront Tailwind et portail MUI sans lib partagée",
        "Auth multi-surfaces — JWT + refresh, middleware chats vs routes admin",
        "Relier fiche produit → conversation → rooms Socket.IO avec Axios SSR-safe",
        "Scoping RBAC — endpoints /my broker vs APIs admin",
        "Livrer le domaine métier sur un héritage template sans full rewrite",
        "Encoder un cycle à six statuts en timeline claire avec upload documents",
        "Vrai i18n/RTL marketplace pendant que le portail restait scaffolding",
      ],
    },
  },
};
